name: 'Terragrunt GitHub Actions'
on:
  - workflow_dispatch

env:
  tf_version: '1.5.7'
  tg_version: '0.53.2'
  working_dir: 'infrastructure-test'
  
permissions:
  id-token: write
  contents: read

jobs:
  terragrunt:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ASSUME_ROLE}}
          aws-region: "eu-west-1"
          
      - name: Validate
        id: validate
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'validate'
      - name: Validate Status
        if: steps.validate.outcome == 'failure'
        run: exit 1
      - name: Plan
        id: plan
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'plan'
      - name: Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      - name: Apply
        id: apply
        uses: gruntwork-io/terragrunt-action@v2
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'apply'
