name: Run SQL Unit Tests

on: push

jobs:
  run_unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: checkout repo
        uses: actions/checkout@main

      - name: Create test database
        run: |
          export PGPASSWORD="testpass"
          psql -h localhost -U testuser -w -d postgres -c "DROP DATABASE testdb;"
          psql -h localhost -U testuser -w -d postgres -c "CREATE DATABASE testdb;"

      - name: Connect to testdb and execute DDL
        run: |
          export PGPASSWORD="testpass"
          psql -h localhost -U testuser -w -d testdb -f "./SQL/DDL/tableCreates.sql"
          psql -h localhost -U testuser -w -d testdb -f "./SQL/DDL/tableAlters.sql"

      - name: Test if clients table is there
        run: |
          export PGPASSWORD="testpass"
          psql -h localhost -U testuser -w -d testdb -f "./SQL/Checks/existence_check.sql"