name: Run SQL Unit Tests

on: push

env:
    PGPASSWORD: "testpass"

jobs:
  run_unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Create test database
        run: |
          psql -h localhost -U testuser -w -d postgres -c "DROP DATABASE testdb;"
          psql -h localhost -U testuser -w -d postgres -c "CREATE DATABASE testdb;"

      - name: Connect to testdb and execute DDL
        run: |
          psql -h localhost -U testuser -w -d testdb -f "./SQL/DDL/tableCreates.sql"
          psql -h localhost -U testuser -w -d testdb -f "./SQL/DDL/tableAlters.sql"

      - name: Test if the tables exists
        run: |
          psql -h localhost -U testuser -w -d testdb -f "./SQL/Checks/existence_check.sql"
      - name: Add dummy data
        run: |
          psql -h localhost -U testuser -w -d testdb -f "./SQL/MockData/exercises.sql"
          psql -h localhost -U testuser -w -d testdb -f "./SQL/MockData/difficulty.sql"
          psql -h localhost -U testuser -w -d testdb -f "./SQL/MockData/programs.sql"
          psql -h localhost -U testuser -w -d testdb -f "./SQL/MockData/program_exercise.sql"
          psql -h localhost -U testuser -w -d testdb -f "./SQL/MockData/clients.sql"
          psql -h localhost -U testuser -w -d testdb -f "./SQL/MockData/client_program.sql"
          psql -h localhost -U testuser -w -d testdb -f "./SQL/MockData/billing.sql"
          psql -h localhost -U testuser -w -d testdb -f "./SQL/MockData/payments.sql"
          